### PR TITLE
Change of LICENSE from GPL to Apache

### PR DESCRIPTION
**Pull request by ekiefl**
Hi @chaochaodev, @edoson, @kerby2000, and @zhaodong-wang

I'm proposing to change pooltool's license from GPLv3 to Apache 2.0. Apache 2.0 is a popular and more permissive license than GPLv3, allowing greater flexibility in how pooltool can be used and incorporated into other projects.

**Important**: As contributors to pooltool, your agreement is needed for this change.

Please reply to this PR with:

**"I approve"** if you agree with the license change.
**Your concerns** if you have any objections.

Thank you for your time and consideration. Additionally, thanks for your past and hopefully future contributions to pooltool!

### CODE REVIEW

**Comment by zhaodong-wang** [comment]
Thanks for the updates! I approve this change

**Comment by ekiefl** [comment]
Anyone else? @chaochaodev, @edoson, @kerby2000

**Comment by chaochaodev** [comment]
I approve! Thank you!

Evan Kiefl ***@***.***> 于2024年4月29日周一 12:19写道：

**Comment by kerby2000** [comment]
I approve.

**Comment by XmanGB32** [comment]
I approve

**Comment by ekiefl** [comment]
The only contributor who hasn't agreed (or disagreed) is @edoson. Though I was hopeful to get everyone's formal approval, I think we're good to move forward regardless.

@edoson has contributed a small amount to the codebase (https://github.com/ekiefl/pooltool/commit/9f1f3bcf61ca50718c7a945097db6ace4af807a0 and https://github.com/ekiefl/pooltool/commit/9f1f3bcf61ca50718c7a945097db6ace4af807a0), but his code was reimplemented by me in the pull request that his commits belonged to (https://github.com/ekiefl/pooltool/pull/55), such that as it stands today, there are no lines attributed to him in the git blame of the main branch.

Thanks for everyone's cooperation, and I hope you all contribute to pooltool in the future.

**Comment by ekiefl** [comment]
Hello again. I am compiling metadata for the project and would like to include all the contributors as authors, if they are interested.

The section I am filling out is for the package manager poetry (section [here](https://python-poetry.org/docs/pyproject/#authors)) and requires authors to have a name and email.

If you are interested in being included in poetry's author metadata, please respond with your name and email. Thanks.

**Pull request merged**
