### PR TITLE
(Partial) Windows support

### PR DESCRIPTION
**Pull request by ekiefl**
The windows API now works, but still waiting for Panda3D 1.11 for relative mouse support. Until then the mouse falls off the window when moving the mouse in Windows. I briefly tried to implement my own relative mode but gave up. If I could install a pre-compiled v1.11 and express that somehow in the `requirements.txt`, then we're in business. Otherwise we wait.

Tagging for relevance: https://github.com/ekiefl/pooltool/issues/50

### CODE REVIEW

**Comment by XmanGB32** [comment]
Just getting into the Github community.  I was looking up billiard sims with ChatGPT and this is what came up: There are several WebGL billiard simulators available online. One example is pooltool, an open-source sandbox billiards game that emphasizes realistic physics. It is designed for both gamers and researchers. Gamers can play different styles of pool (8-ball, 9-ball, etc.) in a 3D-rendered environment that emphasizes physical realism. [Researchers interested in pool physics, game theory, camera-projector systems, AI, robotics, and other billiards-related research topics can efficiently simulate shots using pooltool’s API, experiment with different physics models and shot evolution algorithms, and visualize programmatically-defined shots](https://ekiefl.github.io/projects/pooltool/)[1](https://ekiefl.github.io/projects/pooltool/)

**Comment by HorseEars** [comment]
>  I briefly tried to implement my own relative mode but gave up. If I could install a pre-compiled v1.11 and express that somehow in the `requirements.txt`, then we're in business. Otherwise we wait.

The relative mouse mode is actually a problem in Linux too. That was of the biggest headaches getting it to work. Apparently panda requires libxxf86dga which is sometimes a pain to deal with. It might be worth making our own solution if it's not too difficult.

**Comment by ekiefl** [comment]
> > I briefly tried to implement my own relative mode but gave up. If I could install a pre-compiled v1.11 and express that somehow in the `requirements.txt`, then we're in business. Otherwise we wait.
> 
> The relative mouse mode is actually a problem in Linux too. That was of the biggest headaches getting it to work. Apparently panda requires libxxf86dga which is sometimes a pain to deal with. It might be worth making our own solution if it's not too difficult.

Does it work if you `pip install pooltool-billiards`? Or is libxxf86dga an externally managed dependency?

I could definitely give relative mouse mode another stab. I think I failed the first time because I tried to make the necessary changes while maintaining the overall structure of the `mouse.py` module. If I tried again it would be from scratch.

**Comment by HorseEars** [comment]
libxxf86dga seems to be listed as optional when using panda3d on Linux. This also apparently changes if you're using x11 or wayland display server. I am going to check out installing with pip to see if that just works on ubuntu.

**Pull request merged**
